openapi: 3.0.0
components:
  schemas:
    CurrencyCode:
      example: EUR
      type: string
      format: iso4217-currency-code
      enum:
        - AFN
        - EUR
        - ALL
        - DZD
        - USD
        - AOA
        - XCD
        - ARS
        - AMD
        - AWG
        - AUD
        - AZN
        - BSD
        - BHD
        - BDT
        - BBD
        - BYN
        - BZD
        - XOF
        - BMD
        - INR
        - BTN
        - BOB
        - BOV
        - BAM
        - BWP
        - NOK
        - BRL
        - BND
        - BGN
        - BIF
        - CVE
        - KHR
        - XAF
        - CAD
        - KYD
        - CLP
        - CLF
        - CNY
        - COP
        - COU
        - KMF
        - CDF
        - NZD
        - CRC
        - HRK
        - CUP
        - CUC
        - ANG
        - CZK
        - DKK
        - DJF
        - DOP
        - EGP
        - SVC
        - ERN
        - SZL
        - ETB
        - FKP
        - FJD
        - XPF
        - GMD
        - GEL
        - GHS
        - GIP
        - GTQ
        - GBP
        - GNF
        - GYD
        - HTG
        - HNL
        - HKD
        - HUF
        - ISK
        - IDR
        - XDR
        - IRR
        - IQD
        - ILS
        - JMD
        - JPY
        - JOD
        - KZT
        - KES
        - KPW
        - KRW
        - KWD
        - KGS
        - LAK
        - LBP
        - LSL
        - ZAR
        - LRD
        - LYD
        - CHF
        - MOP
        - MKD
        - MGA
        - MWK
        - MYR
        - MVR
        - MRU
        - MUR
        - XUA
        - MXN
        - MXV
        - MDL
        - MNT
        - MAD
        - MZN
        - MMK
        - NAD
        - NPR
        - NIO
        - NGN
        - OMR
        - PKR
        - PAB
        - PGK
        - PYG
        - PEN
        - PHP
        - PLN
        - QAR
        - RON
        - RUB
        - RWF
        - SHP
        - WST
        - STN
        - SAR
        - RSD
        - SCR
        - SLL
        - SGD
        - XSU
        - SBD
        - SOS
        - SSP
        - LKR
        - SDG
        - SRD
        - SEK
        - CHE
        - CHW
        - SYP
        - TWD
        - TJS
        - TZS
        - THB
        - TOP
        - TTD
        - TND
        - TRY
        - TMT
        - UGX
        - UAH
        - AED
        - USN
        - UYU
        - UYI
        - UYW
        - UZS
        - VUV
        - VES
        - VND
        - YER
        - ZMW
        - ZWL
      x-go-type: github.com/mikekonan/go-currencies/Code
    CurrencyName:
      example: Euro
      type: string
      enum:
        - Afghani
        - Euro
        - Lek
        - Algerian Dinar
        - US Dollar
        - Kwanza
        - East Caribbean Dollar
        - Argentine Peso
        - Armenian Dram
        - Aruban Florin
        - Australian Dollar
        - Azerbaijan Manat
        - Bahamian Dollar
        - Bahraini Dinar
        - Taka
        - Barbados Dollar
        - Belarusian Ruble
        - Belize Dollar
        - CFA Franc BCEAO
        - Bermudian Dollar
        - Indian Rupee
        - Ngultrum
        - Boliviano
        - Mvdol
        - Convertible Mark
        - Pula
        - Norwegian Krone
        - Brazilian Real
        - Brunei Dollar
        - Bulgarian Lev
        - Burundi Franc
        - Cabo Verde Escudo
        - Riel
        - CFA Franc BEAC
        - Canadian Dollar
        - Cayman Islands Dollar
        - Chilean Peso
        - Unidad de Fomento
        - Yuan Renminbi
        - Colombian Peso
        - Unidad de Valor Real
        - "Comorian Franc "
        - Congolese Franc
        - New Zealand Dollar
        - Costa Rican Colon
        - Kuna
        - Cuban Peso
        - Peso Convertible
        - Netherlands Antillean Guilder
        - Czech Koruna
        - Danish Krone
        - Djibouti Franc
        - Dominican Peso
        - Egyptian Pound
        - El Salvador Colon
        - Nakfa
        - Lilangeni
        - Ethiopian Birr
        - Falkland Islands Pound
        - Fiji Dollar
        - CFP Franc
        - Dalasi
        - Lari
        - Ghana Cedi
        - Gibraltar Pound
        - Quetzal
        - Pound Sterling
        - Guinean Franc
        - Guyana Dollar
        - Gourde
        - Lempira
        - Hong Kong Dollar
        - Forint
        - Iceland Krona
        - Rupiah
        - SDR (Special Drawing Right)
        - Iranian Rial
        - Iraqi Dinar
        - New Israeli Sheqel
        - Jamaican Dollar
        - Yen
        - Jordanian Dinar
        - Tenge
        - Kenyan Shilling
        - North Korean Won
        - Won
        - Kuwaiti Dinar
        - Som
        - Lao Kip
        - Lebanese Pound
        - Loti
        - Rand
        - Liberian Dollar
        - Libyan Dinar
        - Swiss Franc
        - Pataca
        - Denar
        - Malagasy Ariary
        - Malawi Kwacha
        - Malaysian Ringgit
        - Rufiyaa
        - Ouguiya
        - Mauritius Rupee
        - ADB Unit of Account
        - Mexican Peso
        - Mexican Unidad de Inversion (UDI)
        - Moldovan Leu
        - Tugrik
        - Moroccan Dirham
        - Mozambique Metical
        - Kyat
        - Namibia Dollar
        - Nepalese Rupee
        - Cordoba Oro
        - Naira
        - Rial Omani
        - Pakistan Rupee
        - Balboa
        - Kina
        - Guarani
        - Sol
        - Philippine Peso
        - Zloty
        - Qatari Rial
        - Romanian Leu
        - Russian Ruble
        - Rwanda Franc
        - Saint Helena Pound
        - Tala
        - Dobra
        - Saudi Riyal
        - Serbian Dinar
        - Seychelles Rupee
        - Leone
        - Singapore Dollar
        - Sucre
        - Solomon Islands Dollar
        - Somali Shilling
        - South Sudanese Pound
        - Sri Lanka Rupee
        - Sudanese Pound
        - Surinam Dollar
        - Swedish Krona
        - WIR Euro
        - WIR Franc
        - Syrian Pound
        - New Taiwan Dollar
        - Somoni
        - Tanzanian Shilling
        - Baht
        - Pa’anga
        - Trinidad and Tobago Dollar
        - Tunisian Dinar
        - Turkish Lira
        - Turkmenistan New Manat
        - Uganda Shilling
        - Hryvnia
        - UAE Dirham
        - US Dollar (Next day)
        - Peso Uruguayo
        - Uruguay Peso en Unidades Indexadas (UI)
        - Unidad Previsional
        - Uzbekistan Sum
        - Vatu
        - Bolívar Soberano
        - Dong
        - Yemeni Rial
        - Zambian Kwacha
        - Zimbabwe Dollar
      x-go-type: github.com/mikekonan/go-currencies/Currency
    CurrencyCountry:
      example: PUERTO RICO
      type: string
      enum:
        - AFGHANISTAN
        - ÅLAND ISLANDS
        - ALBANIA
        - ALGERIA
        - AMERICAN SAMOA
        - ANDORRA
        - ANGOLA
        - ANGUILLA
        - ANTIGUA AND BARBUDA
        - ARGENTINA
        - ARMENIA
        - ARUBA
        - AUSTRALIA
        - AUSTRIA
        - AZERBAIJAN
        - BAHAMAS (THE)
        - BAHRAIN
        - BANGLADESH
        - BARBADOS
        - BELARUS
        - BELGIUM
        - BELIZE
        - BENIN
        - BERMUDA
        - BHUTAN
        - BOLIVIA (PLURINATIONAL STATE OF)
        - BONAIRE, SINT EUSTATIUS AND SABA
        - BOSNIA AND HERZEGOVINA
        - BOTSWANA
        - BOUVET ISLAND
        - BRAZIL
        - BRITISH INDIAN OCEAN TERRITORY (THE)
        - BRUNEI DARUSSALAM
        - BULGARIA
        - BURKINA FASO
        - BURUNDI
        - CABO VERDE
        - CAMBODIA
        - CAMEROON
        - CANADA
        - CAYMAN ISLANDS (THE)
        - CENTRAL AFRICAN REPUBLIC (THE)
        - CHAD
        - CHILE
        - CHINA
        - CHRISTMAS ISLAND
        - COCOS (KEELING) ISLANDS (THE)
        - COLOMBIA
        - COMOROS (THE)
        - CONGO (THE DEMOCRATIC REPUBLIC OF THE)
        - CONGO (THE)
        - COOK ISLANDS (THE)
        - COSTA RICA
        - CÔTE D'IVOIRE
        - CROATIA
        - CUBA
        - CURAÇAO
        - CYPRUS
        - CZECHIA
        - DENMARK
        - DJIBOUTI
        - DOMINICA
        - DOMINICAN REPUBLIC (THE)
        - ECUADOR
        - EGYPT
        - EL SALVADOR
        - EQUATORIAL GUINEA
        - ERITREA
        - ESTONIA
        - ESWATINI
        - ETHIOPIA
        - EUROPEAN UNION
        - FALKLAND ISLANDS (THE) [MALVINAS]
        - FAROE ISLANDS (THE)
        - FIJI
        - FINLAND
        - FRANCE
        - FRENCH GUIANA
        - FRENCH POLYNESIA
        - FRENCH SOUTHERN TERRITORIES (THE)
        - GABON
        - GAMBIA (THE)
        - GEORGIA
        - GERMANY
        - GHANA
        - GIBRALTAR
        - GREECE
        - GREENLAND
        - GRENADA
        - GUADELOUPE
        - GUAM
        - GUATEMALA
        - GUERNSEY
        - GUINEA
        - GUINEA-BISSAU
        - GUYANA
        - HAITI
        - HEARD ISLAND AND McDONALD ISLANDS
        - HOLY SEE (THE)
        - HONDURAS
        - HONG KONG
        - HUNGARY
        - ICELAND
        - INDIA
        - INDONESIA
        - INTERNATIONAL MONETARY FUND (IMF) 
        - IRAN (ISLAMIC REPUBLIC OF)
        - IRAQ
        - IRELAND
        - ISLE OF MAN
        - ISRAEL
        - ITALY
        - JAMAICA
        - JAPAN
        - JERSEY
        - JORDAN
        - KAZAKHSTAN
        - KENYA
        - KIRIBATI
        - KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)
        - KOREA (THE REPUBLIC OF)
        - KUWAIT
        - KYRGYZSTAN
        - LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)
        - LATVIA
        - LEBANON
        - LESOTHO
        - LIBERIA
        - LIBYA
        - LIECHTENSTEIN
        - LITHUANIA
        - LUXEMBOURG
        - MACAO
        - NORTH MACEDONIA
        - MADAGASCAR
        - MALAWI
        - MALAYSIA
        - MALDIVES
        - MALI
        - MALTA
        - MARSHALL ISLANDS (THE)
        - MARTINIQUE
        - MAURITANIA
        - MAURITIUS
        - MAYOTTE
        - MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP
        - MEXICO
        - MICRONESIA (FEDERATED STATES OF)
        - MOLDOVA (THE REPUBLIC OF)
        - MONACO
        - MONGOLIA
        - MONTENEGRO
        - MONTSERRAT
        - MOROCCO
        - MOZAMBIQUE
        - MYANMAR
        - NAMIBIA
        - NAURU
        - NEPAL
        - NETHERLANDS (THE)
        - NEW CALEDONIA
        - NEW ZEALAND
        - NICARAGUA
        - NIGER (THE)
        - NIGERIA
        - NIUE
        - NORFOLK ISLAND
        - NORTHERN MARIANA ISLANDS (THE)
        - NORWAY
        - OMAN
        - PAKISTAN
        - PALAU
        - PANAMA
        - PAPUA NEW GUINEA
        - PARAGUAY
        - PERU
        - PHILIPPINES (THE)
        - PITCAIRN
        - POLAND
        - PORTUGAL
        - PUERTO RICO
        - QATAR
        - RÉUNION
        - ROMANIA
        - RUSSIAN FEDERATION (THE)
        - RWANDA
        - SAINT BARTHÉLEMY
        - SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
        - SAINT KITTS AND NEVIS
        - SAINT LUCIA
        - SAINT MARTIN (FRENCH PART)
        - SAINT PIERRE AND MIQUELON
        - SAINT VINCENT AND THE GRENADINES
        - SAMOA
        - SAN MARINO
        - SAO TOME AND PRINCIPE
        - SAUDI ARABIA
        - SENEGAL
        - SERBIA
        - SEYCHELLES
        - SIERRA LEONE
        - SINGAPORE
        - SINT MAARTEN (DUTCH PART)
        - SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"
        - SLOVAKIA
        - SLOVENIA
        - SOLOMON ISLANDS
        - SOMALIA
        - SOUTH AFRICA
        - SOUTH SUDAN
        - SPAIN
        - SRI LANKA
        - SUDAN (THE)
        - SURINAME
        - SVALBARD AND JAN MAYEN
        - SWEDEN
        - SWITZERLAND
        - SYRIAN ARAB REPUBLIC
        - TAIWAN (PROVINCE OF CHINA)
        - TAJIKISTAN
        - TANZANIA, UNITED REPUBLIC OF
        - THAILAND
        - TIMOR-LESTE
        - TOGO
        - TOKELAU
        - TONGA
        - TRINIDAD AND TOBAGO
        - TUNISIA
        - TURKEY
        - TURKMENISTAN
        - TURKS AND CAICOS ISLANDS (THE)
        - TUVALU
        - UGANDA
        - UKRAINE
        - UNITED ARAB EMIRATES (THE)
        - UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)
        - UNITED STATES MINOR OUTLYING ISLANDS (THE)
        - UNITED STATES OF AMERICA (THE)
        - URUGUAY
        - UZBEKISTAN
        - VANUATU
        - VENEZUELA (BOLIVARIAN REPUBLIC OF)
        - VIET NAM
        - VIRGIN ISLANDS (BRITISH)
        - VIRGIN ISLANDS (U.S.)
        - WALLIS AND FUTUNA
        - WESTERN SAHARA
        - YEMEN
        - ZAMBIA
        - ZIMBABWE
      x-go-type: github.com/mikekonan/go-currencies/Country
    CurrencyNumber:
      example: "840"
      type: string
      enum:
        - "971"
        - "978"
        - "008"
        - "012"
        - "840"
        - "973"
        - "951"
        - "032"
        - "051"
        - "533"
        - "036"
        - "944"
        - "044"
        - "048"
        - "050"
        - "052"
        - "933"
        - "084"
        - "952"
        - "060"
        - "356"
        - "064"
        - "068"
        - "984"
        - "977"
        - "072"
        - "578"
        - "986"
        - "096"
        - "975"
        - "108"
        - "132"
        - "116"
        - "950"
        - "124"
        - "136"
        - "152"
        - "990"
        - "156"
        - "170"
        - "970"
        - "174"
        - "976"
        - "554"
        - "188"
        - "191"
        - "192"
        - "931"
        - "532"
        - "203"
        - "208"
        - "262"
        - "214"
        - "818"
        - "222"
        - "232"
        - "748"
        - "230"
        - "238"
        - "242"
        - "953"
        - "270"
        - "981"
        - "936"
        - "292"
        - "320"
        - "826"
        - "324"
        - "328"
        - "332"
        - "340"
        - "344"
        - "348"
        - "352"
        - "360"
        - "960"
        - "364"
        - "368"
        - "376"
        - "388"
        - "392"
        - "400"
        - "398"
        - "404"
        - "408"
        - "410"
        - "414"
        - "417"
        - "418"
        - "422"
        - "426"
        - "710"
        - "430"
        - "434"
        - "756"
        - "446"
        - "807"
        - "969"
        - "454"
        - "458"
        - "462"
        - "929"
        - "480"
        - "965"
        - "484"
        - "979"
        - "498"
        - "496"
        - "504"
        - "943"
        - "104"
        - "516"
        - "524"
        - "558"
        - "566"
        - "512"
        - "586"
        - "590"
        - "598"
        - "600"
        - "604"
        - "608"
        - "985"
        - "634"
        - "946"
        - "643"
        - "646"
        - "654"
        - "882"
        - "930"
        - "682"
        - "941"
        - "690"
        - "694"
        - "702"
        - "994"
        - "090"
        - "706"
        - "728"
        - "144"
        - "938"
        - "968"
        - "752"
        - "947"
        - "948"
        - "760"
        - "901"
        - "972"
        - "834"
        - "764"
        - "776"
        - "780"
        - "788"
        - "949"
        - "934"
        - "800"
        - "980"
        - "784"
        - "997"
        - "858"
        - "940"
        - "927"
        - "860"
        - "548"
        - "928"
        - "704"
        - "886"
        - "967"
        - "932"
